// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/protected/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute un nouvel utilisateur dans la base de données.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilisateurs"
                ],
                "summary": "Créer un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Données de l'utilisateur à créer",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Utilisateur créé avec succès",
                        "schema": {
                            "$ref": "#/definitions/models.UserSwagger"
                        }
                    },
                    "400": {
                        "description": "Requête invalide, échec de l'analyse du corps de la requête",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Utilisateur déjà existant",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Erreur lors de la création de l'utilisateur",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ActivityStatusSwagger": {
            "type": "object",
            "properties": {
                "birthday": {
                    "description": "Utilise time.Time pour Swagger",
                    "type": "string"
                },
                "lastConnected": {
                    "description": "Utilise time.Time pour Swagger",
                    "type": "string"
                }
            }
        },
        "models.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "citycode": {
                    "type": "string"
                },
                "extra": {
                    "type": "string"
                },
                "floor": {
                    "type": "integer"
                },
                "geopoints": {
                    "$ref": "#/definitions/models.GeoPoints"
                },
                "label": {
                    "type": "string"
                },
                "postcode": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "models.BankInfo": {
            "type": "object",
            "properties": {
                "bic": {
                    "type": "string"
                },
                "iban": {
                    "type": "string"
                }
            }
        },
        "models.GeoPoints": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.UserSwagger": {
            "description": "Modèle d'un utilisateur (utilisé uniquement pour Swagger)",
            "type": "object",
            "required": [
                "email",
                "name",
                "pseudo",
                "surname"
            ],
            "properties": {
                "activityStatus": {
                    "description": "Utilise ActivityStatusSwagger",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ActivityStatusSwagger"
                        }
                    ]
                },
                "address": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Address"
                    }
                },
                "articles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "avatarUrl": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "bankInfo": {
                    "$ref": "#/definitions/models.BankInfo"
                },
                "birthDate": {
                    "type": "string"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "credit": {
                    "type": "number"
                },
                "email": {
                    "type": "string"
                },
                "favoriteArticles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isPremium": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "pseudo": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string",
                    "enum": [
                        "M",
                        "F"
                    ]
                },
                "surname": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Trocup User API",
	Description:      "API pour gérer les utilisateurs sur Trocup",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
